# Generated by Django 4.0.3 on 2022-10-20 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wardrobe_binVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_number', models.PositiveSmallIntegerField()),
                ('import_href', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('shoe_color', models.CharField(max_length=100)),
                ('picture_url', models.URLField()),
                ('wardrobe_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_bin', to='shoes_rest.wardrobe_binvo')),
            ],
        ),
    ]
